### ISSUE TITLE
suggestions for installation.sh file

### ISSUE THREAD

**Issue by robomaniac** [ronnyvdbr/RaspberryIPCamera#15]
I am new the PI and did struggle to install your particular Security Camera module on my Pi.
Here are some suggestions for your installation.sh file

I did try installing line by line and here these are the two things that slow me down. 

Line #147 
```
# edit your fstab file
sudo nano /etc/fstab
```

I was stuck went I read "edit", I was like "edit what!?!". I did not read the next line below. So you could write in the comment
```
# we will now edit the fstab file using nano and add 3 more lines like describe below
sudo nano /etc/fstab
```

at the very end of your file when I was done, I did not understand what to do next. 
you say 
`Final reboot before we can start using our IP Camera`
I was "how", everyone say start the web interface but how? 
Even with your already formatted SD card I did not understand what to do. It's after installing other security/camera software that I knew a little bit more.

I also did not fully understand DHCP and dynamic IP adress.

I was always accessing my PI via VNC viewer and PuTTy. When does did not respond, I was confused.
I simply need to plug HDMI and keyboard to get the IP.

Let say, after line #185 you could add something like this
```
# now plug your HDMI cable into your TV and boot up the PI, you will see on screen
 the boot process then log in using "pi" and "raspberry" for password. Now it is time
 to check the IP of your PI using line command "ifconfig" now go in your computer 
 browser and type that IP address, you will now be able to log  in to the web interface
 with admin as username and raspberry as password.
```

Those are the only two things that bug me since I was new to this Raspberry Pi.

thanks

**Comment by ronnyvdbr** [comment]
Hi, thanks for the suggestion, I have updated the procedure with your comments.
