### ISSUE TITLE
Purple Screen of Death

### ISSUE THREAD

**Issue by flaccidware** [ronnyvdbr/RaspberryIPCamera#16]
This problem is probably all my own making!
I've downloaded the image, burned it to a SD card, booted it.
I can access the web interface fine.  Setting the output to rtsp the going to the site gives me a purple screen.  It appears that the camera was not running so I tried to check it by getting a still image.  The results are shown below as is an attempt to update the firmware as suggested in thew google response.

This solution, if I can get it working is exactly what I need.  Should you require more information please let me know and I will try to provide it.
Regards
Al

**Comment by ronnyvdbr** [comment]
You will need to be more specific.   In default configuration the web camera will run in mjpeg mode and u will be able to via the video feed on the status page.
If you switch the camera to rtsp server mode then it's normal that you are not able to view the video feed on the status page.

**Comment by ronnyvdbr** [comment]
you can check if your camera is detected by running below:
sudo vcgencmd get_camera

**Comment by flaccidware** [comment]
Ronny,
A little knowledge is a dangerous thing.  I assumed the screen was coming from your most excellent program but the issue was in the  VLC configuration I was using as a viewer.
Sorry to bother you
Regards
Al
