### ISSUE TITLE
Password Video streaming

### ISSUE THREAD

**Issue by raspydome** [ronnyvdbr/RaspberryIPCamera#17]
Good morning,
First of all congratulations for their work!
I only have a small problem that is when I enter the URL for streaming video in a browser asks the authentication password and entering in the fields User: admin and password: raspberry makes me authenticate!
I wanted to ask you what credentials I enter to see the straming

Waiting for his kind answer, I wish you best regards Matthias

**Comment by carlosb1** [comment]
I have the same problem..

**Comment by willfu** [comment]
I have the same problem, why this thread was closed...
