### ISSUE TITLE
Installation.sh type-o ?

### ISSUE THREAD

**Issue by szewc83** [ronnyvdbr/RaspberryIPCamera#19]
Hi @ronnyvdbr , 

Is the following line correct?
30 sudo systemctl restart sshd.service

comes back as an error: 
"Failed to restart sshd.service: Unit sshd.service failed to load: No such file or directory." 
![screen 4](https://cloud.githubusercontent.com/assets/25966423/23827756/e692275e-06b2-11e7-82f1-1366c12e0270.jpg)

As you can see if I change it to "sudo systemctl restart ssh.service" it goes through (but I don't know if this is correct)

**Comment by ronnyvdbr** [comment]
hmm, don't know what U are doing but I can't find this in my installation script.
