### ISSUE TITLE
Remembering stage of installation

### ISSUE THREAD

**Issue by chiu0602** [ronnyvdbr/RaspberryIPCamera#2]
While executing "installation.sh", it is required to reboot twice. After reboot, I have to modify "installation.sh" and comment out "Bootstrap" and "Update Firmware" parts and execute the script again.
Is it a good idea that creating a file indicates the installation stages, so that I can execute the script after reboot until the process finish, without comment out the lines?

Btw, thanks for your great work!

**Comment by ronnyvdbr** [comment]
Hi, U are absolutely right, just hadn't the time yet to implement that.
Currently the installation file should not be looked at as an installation script but rather as a sequence of commands to follow to get everything up and running.
But it would be nice to be able to use it as one-shot installation script.
Do u think that modifying the script (removing the firmware update lines) before reboot and entering it in /etc/rc.local for secondary execution would product a one-shot operation?

**Comment by chiu0602** [comment]
Yes, it seems to be an ultimate perfect solution. With the change, I can go away after executing "installation.sh" and wait the installation complete.

**Comment by ronnyvdbr** [comment]
Hi, the installation.sh script is modified to facilitate one-shot operation.
Please be so kind to test it and report if any issue.

**Comment by chiu0602** [comment]
I think it got a typo
`sudo sed -i -e 2,35d /home/pi/RaspberryIPCamera && sudo reboot`
It should be
`sudo sed -i -e 2,35d /home/pi/installation.sh && sudo reboot`

And I am afraid the modification of code by sed may cause confusion when adding or removing lines in the future.

Also, you may consider creating temporary file such as "stage.tmp":

```
if "stage.tmp" exists then
    execute Bootstrap
    execute Update Firmware
    "stage.tmp" content = 1
    insert line in "/etc/rc.local"
    reboot
else if content of "stage.tmp" == 1
    execute Install packages
    "stage.tmp" content = 2
    reboot
else
    rm "stage.tmp"
    remove line in "/etc/rc.local"
```

Sorry my presentation here is not good, wish you understand what I mean. Thanks for your quick response!
