### ISSUE TITLE
Cam stops working after resolution change

### ISSUE THREAD

**Issue by transistorgit** [ronnyvdbr/RaspberryIPCamera#25]
When I set the cam resolution to another value in the web gui, the cam stops working. There is no picture in the status page any more.
Tested with 1.8 beta.

**Comment by chiu0602** [comment]
Same here, here is the log
```
pi@raspberrypi:~ $ sudo journalctl -xn
-- Logs begin at Thu 1970-01-01 00:00:02 UTC, end at Tue 2019-02-05 15:39:34 UTC. --
Feb 05 15:39:34 raspberrypi uv4l_raspicam[2021]: Starting UV4L Raspberry CSI Camera Driver: uv4l
Feb 05 15:39:34 raspberrypi uv4l_raspicam[2021]: <notice> [core] Trying driver 'raspicam' from built-in drivers...
Feb 05 15:39:34 raspberrypi uv4l_raspicam[2021]: <warning> [core] Driver 'raspicam' not found
Feb 05 15:39:34 raspberrypi uv4l_raspicam[2021]: <notice> [core] Trying driver 'raspicam' from external plug-in's...
Feb 05 15:39:34 raspberrypi uv4l_raspicam[2021]: <notice> [driver] Dual Raspicam Video4Linux2 Driver v1.9.48 built Mar 19 2017
Feb 05 15:39:34 raspberrypi uv4l_raspicam[2021]: <error> [core] the argument ('0,0,1920,1080') for option 'preview' is invalid
Feb 05 15:39:34 raspberrypi uv4l_raspicam[2021]: <alert> [core] No device detected
Feb 05 15:39:34 raspberrypi systemd[1]: uv4l_raspicam.service: control process exited, code=exited status=1
Feb 05 15:39:34 raspberrypi systemd[1]: Failed to start LSB: Userspace Camera Driver.
-- Subject: Unit uv4l_raspicam.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit uv4l_raspicam.service has failed.
--
-- The result is failed.
Feb 05 15:39:34 raspberrypi systemd[1]: Unit uv4l_raspicam.service entered failed state.

```

**Comment by chiu0602** [comment]
It works after removing `preview` parameter

1. change the system to read write mode
`sudo mount -o remount,rw / ; sudo mount -o remount,rw /boot`

2. comment out the line with `preview` on file `/etc/uv4l/uv4l-raspicam.conf`

3. comment out the line with `preview` on file `/home/pi/RaspberryIPCamera/www/camera-settings-array.php`

4. reboot

**Comment by ronnyvdbr** [comment]
Very good :-) I wasn't expecting that you would find that out by yourself
...

Op di 5 feb. 2019 om 19:24 schreef chiu0602 <notifications@github.com>:

**Comment by chiu0602** [comment]
@ronnyvdbr Thanks for your camera software, I still cannot find another one better than this, you are the best!

Unlucky my sdcard running with software v1.7 broken, with only 1.8 image, I have to fix it with no choice >.<

Hope that you will put the updated image on web.
