### ISSUE TITLE
Raspberry Zero W + Raspberry Camera v2.1 not working

### ISSUE THREAD

**Issue by renarsvilnis** [ronnyvdbr/RaspberryIPCamera#31]
Unable to get working current `RaspberryPI-IP-Camera-v1.8-beta` release with Raspberry Zero W + Raspberry Camera v2.1.

First it was an issue just to get the Raspberry Zero W to connect to the Wi-Fi as I didn't have a working usb-ethernet adapter. Needed to remount `/etc` as writable so I could edit `/etc/wpa_supplicant/wpa_supplicant.conf`.

Afterwards trough the web interface noticed that there wasn't an camera stream was blank. 

Tried making the file-system readable and running `sudo apt-get update && sudo apt-get upgrade` but it "broke" other components.

Any ideas how can I get it working on my setup?

I also tried putting the sd card in a Raspberry Pi 3 B+, didn't boot passed the "gradient", it showed the undervoltage warning. Don't have a problem with PSU, newer base image versions work great.

**Comment by ronnyvdbr** [comment]
Hi, thats correct,  the version was not designed for zero w.
The zero w does not pack enough horsepower to make the camera streaming without hickups.
