### ISSUE TITLE
cannot view video with manual build live555 and v4l2rtspserver

### ISSUE THREAD

**Issue by chiu0602** [ronnyvdbr/RaspberryIPCamera#4]
With the manual build of live555 and v4l2rtspserver, I cannot start view the camera video through "rstp://...", I cannot found any clue due to my lacking of technical skills, anything I can help?

**Comment by Shogun1978** [comment]
Same problem here, mjpeg works fine with the prepared image over LAN, but no rtsp streaming.

**Comment by ronnyvdbr** [comment]
Hi, kindly advise version that you have this issue with?  Is this also apparent in the latest version available?

**Comment by chiu0602** [comment]
it is due to compilation of package of previous version installation.sh. The bug is invalid now. Thanks.
