### ISSUE TITLE
Could NOT find ALSA in CMake

### ISSUE THREAD

**Issue by lavajgh** [ronnyvdbr/RaspberryIPCamera#7]
I think this is an issue with the RTSP server gitclone, but went to build following the installation.sh and am recieving

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ALSA_LIBRARY (ADVANCED)
    linked by target "h264_v4l2_rtspserver" in directory /home/pi/live/h264_v4l2_rtspserver

**Comment by lavajgh** [comment]
RTSPSERVER now has audio and requires 
sudo apt-get install libasound2-dev

**Comment by ronnyvdbr** [comment]
Hi, thanks for this update, I have updated the installer with your module.
