### ISSUE TITLE
Switch to WiFi doesn't work

### ISSUE THREAD

**Issue by Shogun1978** [ronnyvdbr/RaspberryIPCamera#8]
When I activate the WiFi check box and enter the needed information, the system still stays on LAN connection. Wifi is not working. Using a Edimax adapter, which runs great with raspbian system.
Tried to use the installation.sh to build my own system, but got some errors (two times missing sudo, but even after adding the sudo's, it doesn't work after installation).

**Comment by CoalaJoe** [comment]
Yes. This if fatal.
Doesn't work on my Pi aswell

**Comment by ronnyvdbr** [comment]
Hi, could u kindly confirm which version of the image that you have this issue with?

**Comment by ronnyvdbr** [comment]
Once that u activate the wifi, the Raspberry Pi will have two different IP addresses.  There was indeed a problem viewing the camera image over the wifi, but I have uploaded a new Status.php file which solves this.

**Comment by SamVanHoof** [comment]
I'm using version 1.7 with my raspberry pi 3, I also can't connect to wifi

**Comment by ronnyvdbr** [comment]
Is resolved in version 1.8
